version: '3.8'

services:
  app:
    build: .
    container_name: fitwell-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 3409
      MYSQL_DATABASE: fitwell
      MYSQL_USER: fitwelluser
      MYSQL_PASSWORD: 3409
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
